name: PR Lint Checks

on:
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Check Backend Linting
      working-directory: ./styles/server
      run: |
        npm install
        npm run lint

    - name: Check Frontend Linting
      working-directory: ./styles/client
      run: |
        npm install
        npm run lint
